// API error codes
export const ErrorCode = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_WECHAT_CODE: 'INVALID_WECHAT_CODE',

  // Shop
  SHOP_NOT_FOUND: 'SHOP_NOT_FOUND',
  SHOP_NOT_ACTIVE: 'SHOP_NOT_ACTIVE',
  SHOP_ALREADY_EXISTS: 'SHOP_ALREADY_EXISTS',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_EMPTY: 'ORDER_EMPTY',
  PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE',
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',

  // Address
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_LIMIT_EXCEEDED: 'ADDRESS_LIMIT_EXCEEDED',

  // Merchant
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',

  // Admin
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  INVALID_ADMIN_CREDENTIALS: 'INVALID_ADMIN_CREDENTIALS',

  // Settlement
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',

  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
  PAYMENT_NOT_PAID: 'PAYMENT_NOT_PAID',
  REFUND_FAILED: 'REFUND_FAILED',
  INVALID_PAYMENT_CALLBACK: 'INVALID_PAYMENT_CALLBACK',

  // Upload
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Common
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
